name: Tests and Deploy

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 5.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: yarn test
      - run: EAS_BUILD_AUTOCOMMIT=${{1}} npx eas-cli build --platform all --auto-submit --non-interactive
