name: Tests

on:
  push:
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install
      - run: echo "TEST_LOCAL_SIGNER_KEY=${{ secrets.TEST_LOCAL_SIGNER_KEY }}" > .env.local
      - run: yarn test
